import Head from "next/head"
import cl from "@/styles/Home.module.scss"
import ProductList from "@/components/ProductList"
import { IProduct } from "@/types/IProduct"
import { GetServerSideProps } from "next"

interface HomeProps {
  products: IProduct[]
}

const Home: React.FC<HomeProps> = ({ products }) => {
  return (
    <>
      <Head>
        <title>Azalia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={cl.main}>
        {products ? <ProductList title="Всё для комфортной работы" products={products} /> : <h1>Нет товаров</h1>}
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch("https://fakestoreapi.com/products")
  const data = await res.json()
  return { props: { products: data } }
}

export default Home
